version: '3'
services:
  nebula:
    image: project-ryokocha:latest
    build: .
    container_name: project-ryokocha
    restart: unless-stopped
    ports:
      # DO NOT CHANGE 3000!
      - your port here:3000
